language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
  - client/bower_components
services: mongodb
notifications:
  email: false
sudo: required
branches:
  only:
    - master
before_script:
- npm install -g bower grunt-cli
- bower install
